server:
  port: 8002
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: service1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest