server:
  port: 8003
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest