spring:
  application:
    name: eureka-server
server:
  port: 8761
eureka:
  client:
    fetch-registry: false # 客户端不获取eureka服务器注册表上的注册信息
    register-with-eureka: false # 单点时，不进行自注册
    service-url:
      default-zone: http://localhost:8761/eureka